import { ArrowLeft, Bookmark, Building2, Check, Clock3, MapPin, Share2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'

export default function JobDetail({ jobs, savedIds, onSave, onApply }) {
  const { id } = useParams(); const job = jobs.find((item) => item.id === id)
  if (!job) return <main className="shell not-found"><h1>That role has moved on.</h1><p>The listing may no longer be available.</p><Link to="/" className="primary-button">Explore open roles</Link></main>
  const saved = savedIds.includes(job.id)
  return <main className="shell detail-page"><Link to="/" className="back-link"><ArrowLeft size={16}/> All jobs</Link><div className="detail-layout"><article className="detail-content"><div className="detail-intro"><div className={`company-logo large ${job.logoColor || 'bg-teal-100 text-teal-700'}`}>{job.logo || job.company?.slice(0,2).toUpperCase()}</div><p className="eyebrow">{job.category} · {job.posted}</p><h1>{job.title}</h1><p className="detail-company">{job.company}</p><div className="detail-meta"><span><MapPin size={16}/>{job.location}</span><span>{job.type}</span><span>{job.level}</span></div></div><hr/><section><h2>About the role</h2><p>{job.description}</p><p>We care about craft, momentum, and building an environment where good ideas get a fair hearing. This is a chance to have meaningful ownership while working alongside people who take the work seriously — but not themselves.</p></section><section><h2>What you’ll bring</h2><ul>{job.requirements?.map((item) => <li key={item}><Check size={18}/>{item}</li>)}</ul></section><section><h2>The essentials</h2><div className="essentials"><div><span>Salary range</span><strong>{job.salary}</strong></div><div><span>Workplace</span><strong>{job.type}</strong></div><div><span>Posted</span><strong>{job.posted}</strong></div></div></section></article><aside className="apply-box"><p>Ready for a new chapter?</p><button className="primary-button" onClick={() => onApply(job)}>Apply for this role</button><button className={saved ? 'outline-button saved-detail' : 'outline-button'} onClick={() => onSave(job.id)}><Bookmark size={17} fill={saved ? 'currentColor' : 'none'}/>{saved ? 'Saved to your list' : 'Save this job'}</button><button className="share-button" onClick={() => navigator.clipboard?.writeText(window.location.href)}><Share2 size={16}/> Copy job link</button><small><Clock3 size={14}/> Applications reviewed on a rolling basis.</small></aside></div></main>
}
